name: synthinnotech
description: "SynthInnoTech Company Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  get: ^4.7.2

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.4.0

  # Notifications
  awesome_notifications: ^0.9.3+1

  # UI / Animations
  google_fonts: ^6.3.0
  animate_do: ^4.2.0
  curved_labeled_navigation_bar: ^2.0.6
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  animated_theme_switcher: ^2.0.10

  # Utilities
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
