import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
// Generated by: flutterfire configure
// ignore: depend_on_referenced_packages
import 'package:synthinnotech/firebase_options.dart';

class FirebaseService {
  static bool get isAvailable => Firebase.apps.isNotEmpty;

  static Future<void> initialize() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('Firebase initialized successfully');
    } catch (e) {
      debugPrint('Firebase not configured yet: $e');
    }
  }

  static Future<String?> getFCMToken() async {
    if (!isAvailable) return null;
    try {
      final token = await FirebaseMessaging.instance.getToken();
      debugPrint('FCM Token: $token');
      return token;
    } catch (e) {
      debugPrint('Failed to get FCM token: $e');
      return null;
    }
  }

  static Future<void> setupFCMForegroudListener(
      Function(RemoteMessage) onMessage) async {
    if (!isAvailable) return;
    FirebaseMessaging.onMessage.listen(onMessage);
  }

  static Future<void> setupFCMOpenedListener(
      Function(RemoteMessage) onOpened) async {
    if (!isAvailable) return;
    FirebaseMessaging.onMessageOpenedApp.listen(onOpened);
    final initial = await FirebaseMessaging.instance.getInitialMessage();
    if (initial != null) onOpened(initial);
  }

  static Future<void> requestPermission() async {
    if (!isAvailable) return;
    await FirebaseMessaging.instance.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
  }
}
