// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhI2OqAx0Cq9_RuVYKTWKQsy_RcMNh4E',
    appId: '1:917918626271:web:ac0012a9abc7d55c94946a',
    messagingSenderId: '917918626271',
    projectId: 'synthinnotech-pvt',
    authDomain: 'synthinnotech-pvt.firebaseapp.com',
    storageBucket: 'synthinnotech-pvt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtNqcyAyGtUVB2KSsx_bsja1e1X41UgDA',
    appId: '1:917918626271:android:a92c8d7ddb7c889394946a',
    messagingSenderId: '917918626271',
    projectId: 'synthinnotech-pvt',
    storageBucket: 'synthinnotech-pvt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbZUvd0Uewf3tWaP3zQ03UtNdfIJmhGk',
    appId: '1:917918626271:ios:f7aa842ecb84b8db94946a',
    messagingSenderId: '917918626271',
    projectId: 'synthinnotech-pvt',
    storageBucket: 'synthinnotech-pvt.firebasestorage.app',
    iosBundleId: 'com.example.synthinnotech',
  );
}
